module.exports = {
  resolutions: {
    linux: ['-f', 'dshow', '-list_options', 'true', '-i', '/dev/video0'],
    win: ['-f', 'dshow', '-list_options', 'true', '-i', 'video=Integrated Camera'],
  },
  webm: {
    linux: [
      '-f',
      'v4l2',
      '-framerate',
      '25',
      '-video_size',
      '-i',
      '/dev/video0',
      '-vcodec',
      'libvpx',
      '-b:v',
      '3500k',
      '-r',
      '25',
      '-crf',
      '10',
      '-quality',
      'realtime',
      '-speed',
      '16',
      '-threads',
      '2',
      '-an',
      '-g',
      '25',
      '-f',
      'webm',
    ],
    win: [
      '-rtbufsize',
      '1500M',
      '-f',
      'dshow',
      '-framerate',
      '25',
      '-video_size',
      '-i',
      'video=Integrated Camera',
      '-vcodec',
      'libvpx',
      '-b:v',
      '3500k',
      '-r',
      '25',
      '-crf',
      '10',
      '-quality',
      'realtime',
      '-speed',
      '16',
      '-threads',
      '2',
      '-an',
      '-g',
      '25',
      '-f',
      'webm',
    ],
  },
};
